// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBekHlkqR5KwKLl0vH_5CpwnkradmOt91Y',
    appId: '1:965643333791:web:a799189abe33aa2c9972aa',
    messagingSenderId: '965643333791',
    projectId: 'haja-project',
    authDomain: 'haja-project.firebaseapp.com',
    databaseURL: 'https://haja-project-default-rtdb.firebaseio.com',
    storageBucket: 'haja-project.appspot.com',
    measurementId: 'G-N04NR104NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoyH6ovVntkluOx-zl_9EptWfSfwLoLIM',
    appId: '1:965643333791:android:8c5572a3cd0772b29972aa',
    messagingSenderId: '965643333791',
    projectId: 'haja-project',
    databaseURL: 'https://haja-project-default-rtdb.firebaseio.com',
    storageBucket: 'haja-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB89BtgrvQPmyy9jgdU3GjizlJA0mKU0XI',
    appId: '1:965643333791:ios:3cf57db977d49e279972aa',
    messagingSenderId: '965643333791',
    projectId: 'haja-project',
    databaseURL: 'https://haja-project-default-rtdb.firebaseio.com',
    storageBucket: 'haja-project.appspot.com',
    iosClientId: '965643333791-8ktctasckkuj6agjsncea0emb1i3qbv9.apps.googleusercontent.com',
    iosBundleId: 'com.elistorm.haja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB89BtgrvQPmyy9jgdU3GjizlJA0mKU0XI',
    appId: '1:965643333791:ios:3cf57db977d49e279972aa',
    messagingSenderId: '965643333791',
    projectId: 'haja-project',
    databaseURL: 'https://haja-project-default-rtdb.firebaseio.com',
    storageBucket: 'haja-project.appspot.com',
    iosClientId: '965643333791-8ktctasckkuj6agjsncea0emb1i3qbv9.apps.googleusercontent.com',
    iosBundleId: 'com.elistorm.haja',
  );
}
