name: haja
description: A social ToDo app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.9.2
  day_night_switcher: ^0.2.0+1
  dotted_border: ^2.1.0
  firebase_analytics: ^10.5.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_dynamic_links: ^5.3.6
  firebase_messaging: ^14.6.8
  firebase_storage: ^11.2.7
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_login: ^4.2.1
  flutter_redux: ^0.10.0
  flutter_slidable: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  iconsax: ^0.0.8
  image_picker: ^1.0.4
  intl: ^0.18.1
  number_slide_animation: ^0.2.1
  page_transition: ^2.1.0
  provider: ^6.0.5
  quiver: ^3.2.1
  redux: ^5.0.0
  salomon_bottom_bar: ^3.3.2
  share_plus: ^7.1.0
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          style: italic
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Black.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Bold.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Medium.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Light.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Thin.otf
          weight: 700

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/intro/
    - assets/icons/
    - assets/icons/brands/
    - assets/imports/
