name: haja
description: A social ToDo app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    # dash shell
  google_fonts: ^2.1.0
  flutter_svg: ^1.0.0
  iconsax: ^0.0.8
  salomon_bottom_bar: ^3.1.0
  font_awesome_flutter: ^9.2.0
  fl_chart: ^0.40.2
  flutter_spinkit: ^5.1.0
  table_calendar: ^3.0.3
  # syncfusion_flutter_calendar: ^19.3.57

    # animations
  number_slide_animation: ^0.2.1
  flutter_staggered_animations: ^1.0.0
  page_transition: ^2.0.4
  flutter_slidable: ^1.1.0
  dotted_border: ^2.0.0+1
  day_night_switcher: ^0.2.0+1
  flutter_colorpicker: ^1.0.2
  shimmer: ^2.0.0

    # data management
  provider: ^6.0.1
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  flutter_login: ^3.0.0
  shared_preferences: ^2.0.9
  image_picker: ^0.8.4+4

    # release management
  # upgrader: ^3.5.13
  # flutter_showcase: ^0.1.0

    # firebase
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  firebase_storage: ^10.2.4
  firebase_analytics: ^9.0.4
  cloud_firestore: ^3.1.4
  firebase_messaging: ^11.2.3
  firebase_dynamic_links: ^4.0.2
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^3.5.6+3
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/imports/
