import 'package:cloud_firestore/cloud_firestore.dart';

class MockContent {
  static List<Map<String, dynamic>> get all {
    List<Map<String, dynamic>> list = [];

    for (int i = 0; i < data.length; i++) {
      list.add(data[i]);
    }

    return list;
  }

  static List<Map<String, dynamic>> data = [
    {
      'title': 'Jennie',
      'caption':
          'Just a girl from the New Zealand who moved to Korea to follow my passion',
      'image': '/',
      'sex': 'female',
      'online': true,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'jennie1',
    },
    {
      'title': 'donghee',
      'caption': 'I\'m an actor, but I will never be fake with you ;)',
      'image': '/',
      'sex': 'male',
      'online': false,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'donghee1',
    },
    {
      'title': 'Lee Ji-eun',
      'caption': 'Some people call me IU, but you can call me love',
      'image': '/',
      'sex': 'female',
      'online': true,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'iu1',
    },
    {
      'title': 'Jack Black',
      'caption': 'We came to ROCK!',
      'image': '/',
      'sex': 'male',
      'online': true,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'jackblack1',
    },
    {
      'title': 'Snoop Doggy Dog',
      'caption':
          'if you dont bring some smoke to the golf course... dont worry ill bring it',
      'image': '/',
      'sex': 'male',
      'online': false,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'snoop1',
    },
    {
      'title': 'Tiger Woods',
      'caption': 'I know you know who I am',
      'image': '/',
      'sex': 'male',
      'online': true,
      'verified': false,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'tigerwoods1',
    },
    {
      'title': 'Dorothy Oz',
      'caption': 'I don\'t think I\'m in Kansas anymore...',
      'image': '/',
      'sex': 'female',
      'online': false,
      'verified': false,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'dorothy1',
    },
    {
      'title': 'Jennie',
      'caption':
          'Just a girl from the New Zealand who moved to Korea to follow my passion',
      'image': '/',
      'sex': 'female',
      'online': true,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'jennie2',
    },
    {
      'title': 'donghee',
      'caption': 'I\'m an actor, but I will never be fake with you ;)',
      'image': '/',
      'sex': 'male',
      'online': false,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'donghee2',
    },
    {
      'title': 'Lee Ji-eun',
      'caption': 'Some people call me IU, but you can call me love',
      'image': '/',
      'sex': 'female',
      'online': true,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'iu2',
    },
    {
      'title': 'Jack Black',
      'caption': 'We came to ROCK!',
      'image': '/',
      'sex': 'male',
      'online': true,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'jackblack2',
    },
    {
      'title': 'Snoop Doggy Dog',
      'caption':
          'if you dont bring some smoke to the golf course... dont worry ill bring it',
      'image': '/',
      'sex': 'male',
      'online': false,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'snoop2',
    },
    {
      'title': 'Tiger Woods',
      'caption': 'I know you know who I am',
      'image': '/',
      'sex': 'male',
      'online': true,
      'verified': false,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'tigerwoods2',
    },
    {
      'title': 'Dorothy Oz',
      'caption': 'I don\'t think I\'m in Kansas anymore...',
      'image': '/',
      'sex': 'female',
      'online': false,
      'verified': false,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'dorothy2',
    },
    {
      'title': 'Jennie',
      'caption':
          'Just a girl from the New Zealand who moved to Korea to follow my passion',
      'image': '/',
      'sex': 'female',
      'online': true,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'jennie3',
    },
    {
      'title': 'donghee',
      'caption': 'I\'m an actor, but I will never be fake with you ;)',
      'image': '/',
      'sex': 'male',
      'online': false,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'donghee3',
    },
    {
      'title': 'Lee Ji-eun',
      'caption': 'Some people call me IU, but you can call me love',
      'image': '/',
      'sex': 'female',
      'online': true,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'iu3',
    },
    {
      'title': 'Jack Black',
      'caption': 'We came to ROCK!',
      'image': '/',
      'sex': 'male',
      'online': true,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'jackblack3',
    },
    {
      'title': 'Snoop Doggy Dog',
      'caption':
          'if you dont bring some smoke to the golf course... dont worry ill bring it',
      'image': '/',
      'sex': 'male',
      'online': false,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'snoop3',
    },
    {
      'title': 'Tiger Woods',
      'caption': 'I know you know who I am',
      'image': '/',
      'sex': 'male',
      'online': true,
      'verified': false,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'tigerwoods3',
    },
    {
      'title': 'Dorothy Oz',
      'caption': 'I don\'t think I\'m in Kansas anymore...',
      'image': '/',
      'sex': 'female',
      'online': false,
      'verified': false,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'dorothy3',
    },
    {
      'title': 'Jennie',
      'caption':
          'Just a girl from the New Zealand who moved to Korea to follow my passion',
      'image': '/',
      'sex': 'female',
      'online': true,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'jennie4',
    },
    {
      'title': 'donghee',
      'caption': 'I\'m an actor, but I will never be fake with you ;)',
      'image': '/',
      'sex': 'male',
      'online': false,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'donghee4',
    },
    {
      'title': 'Lee Ji-eun',
      'caption': 'Some people call me IU, but you can call me love',
      'image': '/',
      'sex': 'female',
      'online': true,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'iu4',
    },
    {
      'title': 'Jack Black',
      'caption': 'We came to ROCK!',
      'image': '/',
      'sex': 'male',
      'online': true,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'jackblack4',
    },
    {
      'title': 'Snoop Doggy Dog',
      'caption':
          'if you dont bring some smoke to the golf course... dont worry ill bring it',
      'image': '/',
      'sex': 'male',
      'online': false,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'snoop4',
    },
    {
      'title': 'Tiger Woods',
      'caption': 'I know you know who I am',
      'image': '/',
      'sex': 'male',
      'online': true,
      'verified': false,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'tigerwoods4',
    },
    {
      'title': 'Dorothy Oz',
      'caption': 'I don\'t think I\'m in Kansas anymore...',
      'image': '/',
      'sex': 'female',
      'online': false,
      'verified': false,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'dorothy4',
    },
    {
      'title': 'Jennie',
      'caption':
          'Just a girl from the New Zealand who moved to Korea to follow my passion',
      'image': '/',
      'sex': 'female',
      'online': true,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'jennie5',
    },
    {
      'title': 'donghee',
      'caption': 'I\'m an actor, but I will never be fake with you ;)',
      'image': '/',
      'sex': 'male',
      'online': false,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'donghee5',
    },
    {
      'title': 'Lee Ji-eun',
      'caption': 'Some people call me IU, but you can call me love',
      'image': '/',
      'sex': 'female',
      'online': true,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'iu5',
    },
    {
      'title': 'Jack Black',
      'caption': 'We came to ROCK!',
      'image': '/',
      'sex': 'male',
      'online': true,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'jackblack5',
    },
    {
      'title': 'Snoop Doggy Dog',
      'caption':
          'if you dont bring some smoke to the golf course... dont worry ill bring it',
      'image': '/',
      'sex': 'male',
      'online': false,
      'verified': true,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'snoop5',
    },
    {
      'title': 'Tiger Woods',
      'caption': 'I know you know who I am',
      'image': '/',
      'sex': 'male',
      'online': true,
      'verified': false,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'tigerwoods5',
    },
    {
      'title': 'Dorothy Oz',
      'caption': 'I don\'t think I\'m in Kansas anymore...',
      'image': '/',
      'sex': 'female',
      'online': false,
      'verified': false,
      'created_on': Timestamp.fromDate(DateTime.parse('20210102')),
      'last_login': Timestamp.fromDate(DateTime.now()),
      'id': 'dorothy5',
    },
  ];
}
